{
  "formatVersion": "1.1",
  "component": {
    "group": "com.inkryptvideos.android",
    "module": "inkryptvideos-android",
    "version": "2.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "inkryptvideos-android-2.8.1.aar",
          "url": "inkryptvideos-android-2.8.1.aar",
          "size": 194386,
          "sha512": "108fb786c0aa1b0335ca5200b155b19c08e8baae0ca4654abdb16e279b5df46d616804ca6e175d347759e4b402263f19360340f42d9e9d5d8926e4b150307d04",
          "sha256": "fd5c993729bf2eb74739f3af0eebee38682afc42584325636cb42de6a2a4d6c6",
          "sha1": "26f5188bfd461b99988535ec47f265d99375b6ac",
          "md5": "d9b4d5ab5cc29ecd97737e993b479f84"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.0.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "inkryptvideos-android-2.8.1.aar",
          "url": "inkryptvideos-android-2.8.1.aar",
          "size": 194386,
          "sha512": "108fb786c0aa1b0335ca5200b155b19c08e8baae0ca4654abdb16e279b5df46d616804ca6e175d347759e4b402263f19360340f42d9e9d5d8926e4b150307d04",
          "sha256": "fd5c993729bf2eb74739f3af0eebee38682afc42584325636cb42de6a2a4d6c6",
          "sha1": "26f5188bfd461b99988535ec47f265d99375b6ac",
          "md5": "d9b4d5ab5cc29ecd97737e993b479f84"
        }
      ]
    }
  ]
}
